# Generated by Django 3.1.1 on 2021-02-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191213_1327'),
        ('accounts', '0006_auto_20210212_1539'),
    ]

    operations = [
    ]
